### ISSUE TITLE
ImportError: No module named radiomics

### ISSUE THREAD

**Issue by gregsharp** [Radiomics/SlicerRadiomics#28]
I tried to download and build from source on linux.  It doesn't load, with the following error.  Any idea?  Is it because linux-related issue on the main page?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/PHShome/gcs6/build/slicer-4/SlicerRadiomics-build/inner-build/lib/Slicer-4.7/qt-scripted-modules/SlicerRadiomics.py", line 5, in <module>
    from radiomics import featureextractor, getFeatureClasses, setVerbosity
ImportError: No module named radiomics
loadSourceAsModule - Failed to load file "/PHShome/gcs6/build/slicer-4/SlicerRadiomics-build/inner-build/lib/Slicer-4.7/qt-scripted-modules/SlicerRadiomics.py"  as module "SlicerRadiomics" ! 
Fail to instantiate module  "SlicerRadiomics" 
```

**Comment by fedorov** [comment]
@gregsharp long time no see!

I assume you built using the superbuild approach - can you confirm? Did pyradiomics build as well? Were there any errors?

It is not clear what is the linux-related issue we are experiencing, it might be specific to the dashboard. I can try build/install on linux on Monday when I am back in the office. I am not sure I tried that.

**Comment by fedorov** [comment]
@gregsharp I tried on linux, and I see what you mean. I can't figure out myself how to set up the extra directories so that it can find the dependency python packages! I think it is supposed to somehow configure the launcher with the extra paths, but I don't know how it works. 

@jcfr here is what I tried (to be as close to the dashboard process as possible):

1. Build SlicerRadiomics and then `make package` in `inner-build`
2. Add `<package>/lib/python2.7/site-packages` and `<package>/lib/Slicer-4.7/qt-scripted-modules` in Application settings > Modules extra paths.

This does not work - I cannot import the radiomics package. Do you know what is going on?

Dashboard behavior is different today http://slicer.cdash.org/viewBuildError.php?buildid=1080469 from what we had before in #16. I did not have that problem when I did build+package on my Ubuntu.

**Comment by jcfr** [comment]
In a nutshell, it would be difficult to have a systematic way of inferring the python path based only on the scripted module path.

Manually setting the `PYTHONPATH` allows to address the reported problem. for example:

```
SlicerRadiomics_BUILD_DIR=/home/jcfr/Projects/SlicerRadiomics-Release
PYTHONPATH=$SlicerRadiomics_BUILD_DIR/python-pyradiomics-install/lib/python2.7/site-packages \
  ./Slicer --additional-module-path $SlicerRadiomics_BUILD_DIR/inner-build/lib/Slicer-4.7/qt-scripted-modules/
```

**Comment by fedorov** [comment]
Thank you! I will update the user guide

**Comment by jcfr** [comment]
Update: 

@fedorov The following is a general solution for any extension:

```
build_dir=/home/jcfr/Projects/SlicerRadiomics-Release/inner-build/

./Slicer \
  --launcher-additional-settings $build_dir/AdditionalLauncherSettings.ini \
  --additional-module-path $build_dir
```

**Comment by jcfr** [comment]
>I will update the user guide

The referenced topic should do it

**Comment by fedorov** [comment]
Greg, let us know if this resolved your problems. Sorry for the delay addressing this issue.
