### ISSUE TITLE
Impove Slicer CLI

### ISSUE THREAD

**Issue by jcfr** [Radiomics/SlicerRadiomics#38]
- [x] Add progress reporting
- [x] Intercept logging messages?
- [ ] Make CLI module hidden for users?

Copied from  https://github.com/Radiomics/SlicerRadiomics/pull/37

**Comment by JoostJM** [comment]
Progress reporting is still fairly basic now, it returns the logger output of PyRadiomics and shows some dots accumulating during the extraction.

**Comment by pieper** [comment]
Making the CLI module hidden has been on the wish list before [1].  None of the solutions in that thread are very satisfactory (e.g. putting the CLI in an "Advanced" category).  Even the ugly workaround of removing it from the module menu doesn't work because it still shows up when searching for modules with Control-F.

Probably the best answer would be to add some hint in the xml file and extend the SlicerExecutionModel and the corresponding code in Slicer to respect that flag.  A scripted or loadable module in Slicer can set a 'hidden' property but CLIs cannot currently.

I'm not seeing any other convenient way to hide the CLI.  Suggestions?

[1] http://slicer-devel-archive.65872.n3.nabble.com/Hiding-CLI-from-Slicer-user-interface-td4038452.html#a4038457

**Comment by jcfr** [comment]
> Probably the best answer would be to add some hint in the xml file

Generally speaking, I don't think CLI should dictate if there are visible or not for the user. This is application specific.

Instead, we could:
* add support for hiding CLI from the user (e.g not visible in the menu but still available through python)
* add a Slicer application settings allowing to configure which modules should be hidden from the user.
* agree on a mechanism enabling extension to update/set Slicer settings

**Comment by pieper** [comment]
> Generally speaking, I don't think CLI should dictate if there are visible or not for the user. This is application specific.
That's a good point.

An application setting for which modules to hide could be good.

Another option might be to have a new directory, perhaps called cli-logic-modules or cli-hidden-modules, next to the cli-modules for any clis that the extension would like to have hidden.  Then we would just need to handle that case in the module discovery process.

**Comment by fedorov** [comment]
IMHO and all things considered, I am not convinced focusing on how to hide a CLI is a high enough priority to justify the effort. 

Hiding this one CLI will not make Slicer automagically less confusing, and there is nothing illegitimate in having the "raw" CLI interface. As long as the users know that Radiomics is the main gateway for the analysis, it should be ok. If they start wondering around in the module list, and they don't know what they are doing, they will be lost, and it will not be because of this one CLI.

**Comment by jcfr** [comment]
>  I am not convinced focusing on how to hide a CLI is a high enough priority to justify the effort

Makes sense

> Another option might be to have a new directory, perhaps called cli-logic-modules or cli-hidden-modules

That would work, but the name of directory currently doesn't enforce any behavior. I am not sure this is the right level of abstraction.

**Comment by JoostJM** [comment]
> I am not convinced focusing on how to hide a CLI is a high enough priority to justify the effort

I agree, the CLI is works fine in a stand-alone mode too
