### ISSUE TITLE
voxel based feature extraction

### ISSUE THREAD

**Issue by ajclement** [Radiomics/SlicerRadiomics#54]
I am trying to create a volume with the voxel based Radiomic features? Does anyone know what I may be doing incorrectly.. (see yaml input parameters below).

imageType:
  Original: {}

featureClass:
  ngtdm:

voxelSetting:
  kernelRadius: 3
  maskedKernel: True
  initValue: nan

I am thinking that it may be that pyradiomics had a bug..
https://github.com/Radiomics/pyradiomics/issues/456 

Thanks,
AC

**Comment by JoostJM** [comment]
@ajclement, that bug has since been fixed in the current master.
However, the integration of the voxel-based command line in PyRadiomics is quite new, and we have not yet been able to update the slicer extension to also allow voxel-based extraction.

If you want to extract a voxel-based map, please try using the stand-alone version of PyRadiomics. You can find the details on using PyRadiomics commandline [here](https://pyradiomics.readthedocs.io/en/latest/usage.html#command-line-use).
